[workspace]
members = ["apps/desktop/src-tauri/"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
anyhow = "1.0.75"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
  "parking_lot",
  "tracing",
] }

surrealdb = { version = "1.0.0", default-features = false, features = [
  "kv-rocksdb",
  "kv-speedb",
] }

tokio = { version = "1.34.0", features = ["sync"] }
