[workspace]
members = ["apps/desktop/src-tauri/", "libs/macro-model"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
anyhow = "1.0.80"
thiserror = "1.0.57"

serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
serde_with = { version = "3.6.1" }
ts-rs = { version = "7.1.1", features = [] }
taurpc = "0.2.3"

specta = { version = "2.0.0-rc.7", features = [
  "export",
  "typescript",
  "chrono",
] }
tauri-specta = { version = "2.0.0-rc.4", features = [
  "javascript",
  "typescript",
] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
  "parking_lot",
  "tracing",
] }

surrealdb = { version = "1.2.0", default-features = false, features = [
  "kv-rocksdb",
  "kv-mem",
] }

tokio = { version = "1.36.0", features = ["sync"] }
tokio-util = { version = "0.7.10", features = ["io"] }
chrono = { version = "0.4.34" }
derive_builder = { version = "0.20.0" }
futures = { version = "0.3.30" }
