# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unlicense",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "ISC",
    "MPL-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BUSL-1.1",
    "BSD-3-Clause",
    "Zlib",
    "BSD-2-Clause",
    "OpenSSL",
]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = true

# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
github = ["exoshell-dev"]
