version: '3.9'

services:
  dev:
    image: ghcr.io/ctison/dev
    working_dir: /exoshell
    command: fish -c "mise trust && mise install -y && mise exec -- bun install && sleep inf"
    volumes:
      - ..:/exoshell
