services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        DEVCONTAINER_BASE_DOCKER_IMAGE: ${DEVCONTAINER_BASE_DOCKER_IMAGE}
        DEVCONTAINER_HOST_USERNAME: ${DEVCONTAINER_HOST_USERNAME}
        DEVCONTAINER_HOST_UID: ${DEVCONTAINER_HOST_UID}
        DEVCONTAINER_HOST_GROUPNAME: ${DEVCONTAINER_HOST_GROUPNAME}
        DEVCONTAINER_HOST_GID: ${DEVCONTAINER_HOST_GID}
    volumes:
      - ../:/exoshell
