services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        DEVCONTAINER_BASE_DOCKER_IMAGE: ${DEVCONTAINER_BASE_DOCKER_IMAGE}
        USERNAME: ${USERNAME}
        UID: ${UID}
        GROUPNAME: ${GROUPNAME}
        GID: ${GID}
