name: CI/CD

on:
  pull_request:
  workflow_dispatch:
    inputs:
      # environment:
      #   description: Environment to deploy
      #   required: true
      #   default: staging
      #   type: choice
      #   options:
      #     - staging
      #     - production
      should-ci:
        description: CI y/n ?
        type: boolean
        required: true
        default: true
      should-cd:
        description: CD y/n ?
        type: boolean
        required: true
        default: false
      version:
        description: Package version
        type: string
        required: true
        default: 'v0.0.0-alpha.1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    strategy:
      fail-fast: true
    runs-on: ubuntu-22.04
    if: (github.event.inputs.should_ci == true && github.event_name == 'workflow_dispatch') || github.event_name == 'pull_request'
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Compute variables
        uses: actions/github-script@v7
        id: variables
        with:
          script: (await import('${{ github.workspace }}/.github/scripts/compute-variables.mjs')).default(context, core)

      - uses: oven-sh/setup-bun@v1

      - name: Install > Lint > Test
        run: |
          bun install --frozen-lockfile
          bun run ci

  cd:
    strategy:
      # TODO should be true, false while we iterate
      fail-fast: false
      # Missing architectures: Linux [ARMv7, ARMv8]
      matrix:
        settings:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
    runs-on: ${{ matrix.settings.platform}}
    if: github.event.inputs.should_cd == true && github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Compute variables
        uses: actions/github-script@v7
        id: variables
        with:
          script: (await import('${{ github.workspace }}/.github/scripts/compute-variables.mjs')).default(context, core)

      - name: Install dependencies (ubuntu platform only)
        if: matrix.settings.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: oven-sh/setup-bun@v1

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install
        run: |
          bun install --frozen-lockfile

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '${{ github.workspace }}/apps/desktop/src-tauri -> target'

      - name: Compute package version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./apps/desktop
          tauriScript: bun tauri
          args: ${{ matrix.settings.args }}
          tagName: v${{ steps.version.outputs.version }}
          releaseName: 'Exoshell v${{ steps.version.outputs.version }}'
          releaseBody: ''
          # includeUpdaterJson: true
          # releaseDraft: true
          # prerelease: false
