name: CI/CD

on:
  push:
    tags:
      - v*
      - desktop/v*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    outputs:
      shouldRelease: ${{ steps.compute_variables.outputs.shouldRelease }}
      appVersion: ${{ steps.compute_variables.outputs.appVersion }}
      cdTauriMatrix: ${{ steps.compute_variables.outputs.cdTauriMatrix }}
      rustVersion: ${{ steps.compute_variables.outputs.rustVersion }}
      releaseVersion: ${{ steps.compute_variables.outputs.releaseVersion }}
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: Mozilla-Actions/sccache-action@v0.0.4
      - run: bun install --frozen-lockfile
      - name: Compute variables
        uses: actions/github-script@v7
        id: compute_variables
        with:
          script: (await import('${{ github.workspace }}/.github/scripts/computeVariables.mjs')).default(context, core)
      - name: Install Tauri system dependencies
        uses: ./.github/actions/tauri-install-system-deps
      - name: Lint & Test
        run: |
          bun run ci
          cargo test --locked ${{ github.workspace }}
      # - uses: EmbarkStudios/cargo-deny-action@v1
      #   with:
      #     rust-version: ${{ format('{0}.0', steps.compute_variables.outputs.rustVersion) }}
      #     command: check bans licenses sources

  cd-cli:
    timeout-minutes: 60
    needs: [ci]
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-freebsd
            bin: exoshell
            name: cli-exoshell-FreeBSD-x86_64.tar.gz
            command: both
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: exoshell.exe
            name: cli-exoshell-Windows-x86_64.zip
            command: both
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: exoshell
            name: cli-exoshell-Darwin-x86_64.tar.gz
            command: both
          - release_for: macOS-arm64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: exoshell
            name: cli-exoshell-Darwin-arm64.tar.gz
            command: both
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Override version
        run: |
          if "$(uname -s)" = "Darwin"; then
            SED="sed -i ''"
          else
            SED="sed -i"
          fi
          $SED -E 's/^version = ".+"$/version = "${{ needs.ci.outputs.releaseVersion }}"/' Cargo.toml
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: '--locked --release'
          strip: true
          working-directory: ./apps/cli/
      - name: Build cross platforms
        run: |
          mkdir tmp/
          mv ./target/aarch64-unknown-linux-gnu/release/base-converter ./tmp/base-converter-aarch64-unknown-linux-gnu
          mv ./target/aarch64-unknown-linux-musl/release/base-converter ./tmp/base-converter-aarch64-unknown-linux-musl
          mv ./target/x86_64-unknown-linux-gnu/release/base-converter ./tmp/base-converter-x86_64-unknown-linux-gnu
          mv ./target/x86_64-unknown-linux-musl/release/base-converter ./tmp/base-converter-x86_64-unknown-linux-musl
          mv ./target/x86_64-pc-windows-gnu/release/base-converter.exe ./tmp/base-converter-x86_64-pc-windows-gnu.exe
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: cli-${{ matrix.os }}
          path: tmp/

  cd-tauri:
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.ci.outputs.cdTauriMatrix) }}
    runs-on: ${{ matrix.platform}}
    timeout-minutes: 60
    needs: [ci]
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ needs.ci.outputs.rustVersion }}
          targets: ${{ matrix.rustTargets || matrix.tauriBuildTarget }}
      - uses: Mozilla-Actions/sccache-action@v0.0.4
      - run: bun install --frozen-lockfile
      - name: Install Tauri system dependencies
        uses: ./.github/actions/tauri-install-system-deps
      - name: Generate Typescript types from Rust
        run: bun run gen:types
      - name: Inject app version in Cargo.toml
        run: sed -i=bak 's/version = "0.0.0"/version = "${{ needs.ci.outputs.appVersion }}"/' Cargo.toml
      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ./apps/desktop
          appVersion: ${{ needs.ci.outputs.appVersion }}
          tauriScript: bun tauri
          args: ${{ format('--target {0}', matrix.tauriBuildTarget) }}
      - uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.tauriBuildTarget }}
          path: |-
            ${{ join(fromJSON(steps.tauri.outputs.artifactPaths), '
            ') }}
          if-no-files-found: error

  release:
    if: needs.ci.outputs.shouldRelease != 'false'
    needs: [ci, cd-tauri]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          path: desktop/
          pattern: desktop-**
      - name: Prepare release
        uses: actions/github-script@v7
        with:
          script: (await import('${{ github.workspace }}/.github/scripts/prepareRelease.mjs')).default(context, 'v${{ needs.ci.outputs.releaseVersion }}')
      - uses: softprops/action-gh-release@v2
        with:
          name: ExoShell v${{ needs.ci.outputs.releaseVersion }}
          draft: ${{ needs.ci.outputs.shouldRelease == 'draft' }}
          prerelease: ${{ needs.ci.outputs.shouldRelease == 'prerelease' || needs.ci.outputs.shouldRelease == 'draft' }}
          files: |
            updater.json
            desktop/**/*.tar.gz
            desktop/**/*.tar.gz.sig
            desktop/**/*.dmg
            desktop/**/*.deb
            desktop/**/*.AppImage
            desktop/**/*.msi
            desktop/**/*.exe
            desktop/**/*.zip
            desktop/**/*.zip.sig
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: ${{ needs.ci.outputs.shouldRelease == 'stable' && 'true' || 'false' }}
