name: CI/CD

on:
  push:
    # branches:
    #   - main
    tags:
      - v*
      # - desktop/v*
      # - cli/v*
      # - mobile/v*
      # - web/v*
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy ?
        type: choice
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
      always-ci:
        description: Force CI step y/n ?
        type: boolean
        required: true
        default: true
      always-cd:
        description: Force CD step y/n ?
        type: boolean
        required: true
        default: false
      dry-run-cd:
        description: Dry-run CD step y/n ?
        type: boolean
        required: true
        default: false
      version:
        description: Package version (relevant if you trigger this job by workflow_dispatch)
        type: string
      build-desktop:
        description: Build desktop y/n ?
        type: boolean
        required: true
        default: true
      build-cli:
        description: Build cli y/n ?
        type: boolean
        required: true
        default: true
      build-mobile:
        description: Build mobile y/n ?
        type: boolean
        required: true
        default: true
      build-web:
        description: Build web y/n ?
        type: boolean
        required: true
        default: true
      # Missing architectures: Linux [ARMv7, ARMv8], MacOs [Universal]
      target-linux:
        description: Target Linux y/n ? (relevant for desktop)
        type: boolean
        required: true
        default: true
      target-macos:
        description: Target MacOs y/n ? (relevant for desktop)
        type: boolean
        required: true
        default: true
      target-windows:
        description: Target Windows y/n ? (relevant for desktop)
        type: boolean
        required: true
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      environment: ${{ steps.set_vars.outputs.environment }}
      always-ci: ${{ steps.set_vars.outputs.always-ci }}
      always-cd: ${{ steps.set_vars.outputs.always-cd }}
      dry-run-cd: ${{ steps.set_vars.outputs.dry-run-cd }}
      version: ${{ steps.set_vars.outputs.version }}
      build-desktop: ${{ steps.set_vars.outputs.build-desktop }}
      build-cli: ${{ steps.set_vars.outputs.build-cli }}
      build-mobile: ${{ steps.set_vars.outputs.build-mobile }}
      build-web: ${{ steps.set_vars.outputs.build-web }}
      target-linux: ${{ steps.set_vars.outputs.target-linux }}
      target-macos: ${{ steps.set_vars.outputs.target-macos }}
      target-windows: ${{ steps.set_vars.outputs.target-windows }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute variables
        uses: actions/github-script@v7
        id: set_vars
        with:
          script: (await import('${{ github.workspace }}/.github/scripts/compute-variables.mjs')).default(context, core)

  ci:
    runs-on: ubuntu-22.04
    if: >-
      needs.setup.outputs.always-ci || 
      github.event_name == 'pull_request'
    timeout-minutes: 5
    permissions:
      contents: read
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install > Lint > Test
        run: |
          bun install --frozen-lockfile
          bun run ci

  cd:
    runs-on: ${{ matrix.settings.platform}}
    if: >-
      needs.setup.outputs.always-cd ||
      (github.event_name == 'push' &&
      (startsWith(github.ref, 'refs/tags/v') ||
      startsWith(github.ref, 'refs/tags/desktop/v') ||
      startsWith(github.ref, 'refs/tags/cli/v') ||
      startsWith(github.ref, 'refs/tags/mobile/v') ||
      startsWith(github.ref, 'refs/tags/web/v')))
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      # TODO should be true, false while we iterate
      fail-fast: false
      matrix:
        settings:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Compute variables
        uses: actions/github-script@v7
        id: variables
        with:
          script: (await import('${{ github.workspace }}/.github/scripts/compute-variables.mjs')).default(context, core)

      - name: Install dependencies (Linux only)
        if: matrix.settings.platform == 'ubuntu-22.04'
        # libwebkit2gtk-4.0-dev == needed for Tauriv1
        # libwebkit2gtk-4.1-dev == needed for Tauriv2
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies (MacOs only)
        if: matrix.settings.platform == 'macos-latest'
        run: |
          brew install llvm@14
          export PATH="/opt/homebrew/opt/llvm@14/bin:$PATH"

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: oven-sh/setup-bun@v1

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install
        run: |
          bun install --frozen-lockfile

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '${{ github.workspace }}/apps/desktop/src-tauri -> target'

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./apps/desktop
          tauriScript: bun tauri
          args: ${{ matrix.settings.args }}
          tagName: ${{ needs.setup.outputs.version }}
          releaseName: 'Exoshell v${{ needs.setup.outputs.version }}'
          releaseBody: ''
          # includeUpdaterJson: true
          # releaseDraft: true
          # prerelease: false
